name: tmed_kiosk
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  shimmer: ^3.0.0
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path: ^1.9.0
  image: ^4.1.7
  web_socket_channel: ^2.4.4
  pretty_dio_logger: ^1.3.1
  dropdown_button2: ^2.3.9
  flutter_widget_from_html: ^0.14.11
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  lottie: ^3.0.0
  qr_code_scanner: ^1.0.1
  keyboard_dismisser: ^3.0.0
  get_it: ^7.6.7
  printing: ^5.12.0
  pdf: ^3.10.8
  syncfusion_flutter_sliders: ^25.1.35
  syncfusion_flutter_charts: ^25.1.35
  responsive_framework: ^1.4.0
  teledart: ^0.6.1
  fl_chart: ^0.66.2
  camera_platform_interface: ^2.7.4
  camera_macos: ^0.0.8
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  easy_localization: ^3.0.5
  mask_text_input_formatter: ^2.9.0
  audioplayers: ^6.0.0
  dio: ^5.4.2+1
  intl: ^0.18.1
  logger: ^2.2.0
  go_router: ^13.2.1
  ffi: ^2.1.2
  easy_date_timeline: ^1.0.3
  table_calendar: ^3.0.9
  visibility_detector: ^0.4.0+2
  flutter_barcode_listener: ^0.1.4
  qr_flutter: ^4.1.0
#  flutter_tts: ^4.0.2
  kiosk_mode: ^0.5.0+2
  # camera_windows:
  #   git:
  #     url: https://github.com/yushulx/flutter_camera_windows.git
  # flutter_barcode_sdk: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  rename: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/
    - lib/assets/strings/
    - assets/notif.mp3
    - assets/icons/language-circle.svg
    - assets/icons/dollar-circle.svg
    - assets/icons/logout.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial_bolditalicmt.ttf
        - asset: assets/fonts/ArialMonoMTProRegular.TTF
    - family: Courier
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
