name: tmed_kiosk
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  hive: ^2.2.3
  shimmer: ^3.0.0
  json_annotation: ^4.8.1
  carousel_slider: ^5.0.0
  image_picker: ^1.0.0
  cached_network_image: ^3.4.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  path: ^1.9.0
  image: ^4.2.0
  web_socket_channel: ^3.0.1
  pretty_dio_logger: ^1.4.0
  dropdown_button2: ^2.3.9
  flutter_widget_from_html: ^0.15.2
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  keyboard_dismisser: ^3.0.0
  get_it: ^8.0.0
  printing: ^5.13.3
  pdf: ^3.11.1
  syncfusion_flutter_sliders: ^25.2.7
  syncfusion_flutter_charts: ^25.2.7
  responsive_framework: ^1.5.1
  teledart: ^0.6.1
  fl_chart: ^0.69.0
  camera_platform_interface: ^2.8.0
  camera_macos: ^0.0.9
  flutter_bloc: ^8.1.6
  formz: ^0.7.0
  easy_localization: ^3.0.7
  mask_text_input_formatter: ^2.9.0
  audioplayers: ^6.1.0
  logger: ^2.4.0
  go_router: ^14.3.0
  ffi: ^2.1.3
  easy_date_timeline: ^1.1.3
  table_calendar: ^3.1.2
  visibility_detector: ^0.4.0+2
  flutter_barcode_listener: ^0.1.4
  qr_flutter: ^4.1.0
  # kiosk_mode: ^0.5.1
  flutter_tts: ^4.0.2
  # panorama_viewer: ^2.0.0
  http: ^1.2.2
  open_app_file: ^4.0.2
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  html: ^0.15.4
  panorama_viewer: ^1.0.6
  circular_countdown_timer: ^0.2.3
  kiosk_mode: ^0.5.1
  qr_code_scanner: ^0.4.0
  # circular_countdown_timer: ^0.2.4
  # camera_windows:
  #   git:
  #     url: https://github.com/yushulx/flutter_camera_windows.git
  # flutter_barcode_sdk: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  rename: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/
    - lib/assets/strings/
    - assets/notif.mp3
    - assets/icons/language-circle.svg
    - assets/icons/dollar-circle.svg
    - assets/icons/logout.svg

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial_bolditalicmt.ttf
        - asset: assets/fonts/ArialMonoMTProRegular.TTF
    - family: Courier
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
